version: 0.2

env:
  variables:
    AWS_REGION: "eu-north-1"
    AWS_ACCOUNT_ID    : "295367350923"
    ECR_REPO_NAME     : "demo-app"
    ECR_IMAGE_TAG     : "latest"

phases:
  pre_build:
    commands:
      - echo "Login into AWS ECR"
      - aws ecr get-login-password --region $AWS_REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Build the Docker image and tag it"
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG

  post_build:
    commands:
      - echo "Push the Docker image  to the ECR"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
